name: Basic Workflow

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  basic-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Run basic command
        run: |
          echo "Hello, world!"
          node --version
          npm --version
      
      - name: Install dependencies
        run: |
          npm install --no-package-lock
        
      - name: Run article scraper
        run: node scripts/test-full-process.js
        env:
          # WordPress.com API Configuration
          WORDPRESS_API_URL: "https://public-api.wordpress.com/wp/v2/sites/fumixo5.wordpress.com"
          WORDPRESS_USERNAME: "fuminozawa246"
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          # WordPress.com OAuth credentials
          WORDPRESS_CLIENT_ID: "116326"
          WORDPRESS_CLIENT_SECRET: ${{ secrets.WORDPRESS_CLIENT_SECRET }}
          
          # OpenRouter API Configuration
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          
          # Site URL
          NEXT_PUBLIC_SITE_URL: "https://www.unmanned-newsroom.com/"
          
          # Target website to scrape (optional)
          TARGET_WEBSITE: https://techcrunch.com/category/artificial-intelligence/
